/**
 * Version sync script
 * Reads version.json and syncs version to package.json, tauri.conf.json, and Cargo.toml
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const versionFile = path.join(rootDir, 'version.json');

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function writeJson(filePath, data) {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
}

function updateCargoToml(filePath, version) {
  let content = fs.readFileSync(filePath, 'utf-8');
  content = content.replace(
    /^version\s*=\s*"[^"]*"/m,
    `version = "${version}"`
  );
  fs.writeFileSync(filePath, content);
}

function main() {
  console.log('Syncing version...');
  
  // Read version source
  const versionData = readJson(versionFile);
  const fullVersion = versionData.version;
  
  console.log(`Version: ${fullVersion}`);
  console.log(`Build: ${versionData.build}`);
  
  // Sync package.json
  const packageJsonPath = path.join(rootDir, 'package.json');
  const packageJson = readJson(packageJsonPath);
  packageJson.version = fullVersion;
  writeJson(packageJsonPath, packageJson);
  console.log('Updated package.json');
  
  // Sync tauri.conf.json
  const tauriConfPath = path.join(rootDir, 'src-tauri', 'tauri.conf.json');
  const tauriConf = readJson(tauriConfPath);
  tauriConf.version = fullVersion;
  writeJson(tauriConfPath, tauriConf);
  console.log('Updated tauri.conf.json');
  
  // Sync Cargo.toml
  const cargoTomlPath = path.join(rootDir, 'src-tauri', 'Cargo.toml');
  updateCargoToml(cargoTomlPath, fullVersion);
  console.log('Updated Cargo.toml');
  
  // Generate version info for frontend
  const versionTsPath = path.join(rootDir, 'src', 'version.ts');
  const versionTs = `// Auto-generated by scripts/sync-version.cjs
// Do not edit manually

export const APP_VERSION = 'v${fullVersion}';
export const BUILD_NUMBER = '${versionData.build}';
export const APP_NAME = '${versionData.name}';
export const VERSION_INFO = {
  version: '${fullVersion}',
  build: '${versionData.build}',
  name: '${versionData.name}',
  displayVersion: 'v${fullVersion}',
  fullVersion: 'v${fullVersion}+${versionData.build}'
};
`;
  fs.writeFileSync(versionTsPath, versionTs);
  console.log('Generated src/version.ts');
  
  console.log('Version sync complete!');
}

main();
