// Auto-generated by scripts/sync-version.cjs
// Do not edit manually

export const APP_VERSION = 'v1.0.2';
export const BUILD_NUMBER = '20251221';
export const APP_NAME = 'InterviewSpark';
export const VERSION_INFO = {
  version: '1.0.2',
  build: '20251221',
  name: 'InterviewSpark',
  displayVersion: 'v1.0.2',
  fullVersion: 'v1.0.2+20251221'
};
