// Auto-generated by scripts/sync-version.cjs
// Do not edit manually

export const APP_VERSION = 'v1.1.1';
export const BUILD_NUMBER = '20251221';
export const APP_NAME = 'InterviewSpark';
export const VERSION_INFO = {
  version: '1.1.1',
  build: '20251221',
  name: 'InterviewSpark',
  displayVersion: 'v1.1.1',
  fullVersion: 'v1.1.1+20251221'
};
