// Auto-generated by scripts/sync-version.cjs
// Do not edit manually

export const APP_VERSION = 'v1.2.0';
export const BUILD_NUMBER = '20251221';
export const APP_NAME = 'InterviewSpark';
export const VERSION_INFO = {
  version: '1.2.0',
  build: '20251221',
  name: 'InterviewSpark',
  displayVersion: 'v1.2.0',
  fullVersion: 'v1.2.0+20251221'
};
